# Generated by Django 4.1.3 on 2022-11-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=64, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=32)),
                ('permgroup', models.IntegerField(db_column='PermGroup')),
                ('regdate', models.DateTimeField(db_column='RegDate')),
                ('email', models.CharField(db_column='Email', max_length=320, unique=True)),
                ('nickname', models.CharField(db_column='Nickname', max_length=32)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
